### ISSUE TITLE
Remove tdewolff

### ISSUE THREAD

**Issue by Brooooooklyn** [privatenumber/minification-benchmarks#223]
https://www.npmjs.com/package/@tdewolff/minify it's like a toy project, with **62 Weekly downloads**.

**Comment by paulocoghi** [comment]
_(Disclaimer: I'm not a `tdewolff/minify` contributor nor maintainer)_

I respectfully disagree for the following reasons:

- it has merits, including the fastest minification time across (practically) all tests, with uncontested speed
- since it's made in Golang, it also provide CLI binaries, making npm just one medium of distribution
- if it was a toy project, wow... the "production grade" ones have a lot to improve to be _less distant_ to its speed
- even without a meritocratic POV, `tdewolff/minify` has 3k+ stars on Github, is actively maintained and more than 30+ contributors

**Comment by privatenumber** [comment]
Thanks @paulocoghi.

I will not be removing [`tdewolff/minify`](https://github.com/tdewolff/minify). It's a serious project with one of the best performances.

Unfortunately, their [npm distribution currently has a bug](https://github.com/tdewolff/minify/issues/519) that's preventing further adoption.

**Comment by Brooooooklyn** [comment]
I thought it was a toy project because:

1. https://github.com/tdewolff/minify/runs/8104468113?check_suite_focus=true the latest CI shows it didn't run with many platforms because of segmentation fault and core dumped.
2. https://github.com/tdewolff/minify/blob/master/js/stmtlist.go#L72-L88 there are bunches of codes like this
