### ISSUE TITLE
Set minified output target, fix questionable results

### ISSUE THREAD

**Issue by guilhermesimoes** [privatenumber/minification-benchmarks#417]
### Feature request

There's a very big difference in minifying output for a ES2018 target or a ES5 target.

This is ES2018:
```js
var foo = 1;
var bar = 2;
{ foo, bar }
```
And this is ES5:
```js
var foo = 1;
var bar = 2;
{ foo: foo, bar: bar }
```

Currently, not all tools are minifying to the same target. For example, Terser has the default target of ES5 while esbuild has the default target of ES2018.

This means that the current results are not accurate and do not represent what each tool can accomplish.

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
You can see how each minifier is configured here: https://github.com/privatenumber/minification-benchmarks/tree/master/lib/minifiers

**Comment by guilhermesimoes** [comment]
Hmm, that means that there is currently no minified output target. There definitely should be one.

For example, here's [ESBuild's docs](https://esbuild.github.io/api/#target):

> The default target is esnext which means that by default, esbuild will assume all of the latest JavaScript and CSS features are supported.

And here's [Terser's docs](https://terser.org/docs/api-reference/#minify-options):

> ecma (default 5) -- set desired EcmaScript standard version for output. Set ecma to 2015 or greater to emit shorthand object properties - i.e.: {a} instead of {a: a}. The ecma option will only change the output in direct control of the beautifier. Non-compatible features in your input will still be output as is. For example: an ecma setting of 5 will not convert modern code to ES5.

I have no idea what the other tools' default are. But without configuring this field on all tools, we're currently comparing apples to oranges.

**Comment by privatenumber** [comment]
I disagree it's apples to oranges, or that setting a syntax target will yield a drastic improvement. But there's only one way to find out and I would be happy to be proven wrong. PR welcome!

---

Some points to consider:

- These benchmarks are designed for the average user who prefers to plug-and-play with minimal configuration, and may not bother with fine-tuning the minifiers for optimal output. For them, it's fairer and more insightful to compare average setup rather than configurations tweaked for a specific target.

- With gzip compression, syntax level patterns can be reduced. Since we primarily care about over-the-wire size, I'm skeptical setting the target will yield a notable difference.

- Most of these minifiers are using default or minimal configurations recommended by the minifiers documentation. I'm also sure the maintainers are aware of these benchmarks; if they also disagree with how they're compared, they can either open an issue here or update their defaults / docs.

- Not all minifiers support passing in a syntax target, or the latest syntax. It may not be fair to compare minifiers that don't even have the feature to minifiers that do.

- In real-world scenarios, a lot of minified code is applied to transpiled code (e.g., Babel output), making it challenging for minifiers to reverse even with a higher syntax target.

**Comment by guilhermesimoes** [comment]
> These benchmarks are designed for the average user who prefers to plug-and-play with minimal configuration, and may not bother with fine-tuning the minifiers for optimal output. For them, it's fairer and more insightful to compare average setup rather than configurations tweaked for a specific target.

That's not written anywhere on the README.
Furthermore, this is Terser's config:
https://github.com/privatenumber/minification-benchmarks/blob/d9130c81de08f8d26cfb88ca37a7693e7c5eac4d/lib/minifiers/terser.ts#L6-L9
And this is Babel's:
https://github.com/privatenumber/minification-benchmarks/blob/d9130c81de08f8d26cfb88ca37a7693e7c5eac4d/lib/minifiers/babel-minify.ts#L6-L7
Why does esbuild have this config:
https://github.com/privatenumber/minification-benchmarks/blob/d9130c81de08f8d26cfb88ca37a7693e7c5eac4d/lib/minifiers/esbuild.ts#L6-L9
?

Why does esbuild have 2 more options than the others? Doesn't seem like the average setup.

> With gzip compression, syntax level patterns can be reduced. Since we primarily care about over-the-wire size, I'm skeptical setting the target will yield a notable difference.

Skeptical? We should be more curious and scientific and actually try stuff before making (possibly wrong) assumptions.

> Most of these minifiers are using default or minimal configurations recommended by the minifiers documentation.

Where in esbuild's documentation does it say to use `legalComments` and `treeShaking`?

> It may not be fair to compare minifiers that don't even have the feature to minifiers that do.

By your own logic, since other minifiers don't have the options `legalComments` and `treeShaking` then you shouldn't enable them on esbuild.

**Comment by privatenumber** [comment]
The results were basically the same for both of them (with `passes` being slower), so I think it was a pretty fair comparison to start with.

Thanks for the experiments!

**Comment by guilhermesimoes** [comment]
Btw I don't think you should have closed this issue because other tools may also be using ES5. I just gave Terser as an example of a tool that I knew wasn't properly configured for the comparison to be fair. It's possible other tools are also being unfairly compared.
